---
- name: process ports of windows host
  hosts: jon
  gather_facts: false
  tasks:
   - name: finding process ports
     win_shell: netstat -n
     #win_shell: netstat -o -p tcp | Select-String ':5986'
     register: process_ports
   - name: displaying process ports
     debug:
       msg: "{{ process_ports.stdout_lines }}"
   #- name: listen_port_facts
    # listen_ports_facts:
